version: '3.7'
services:
  calisthenics-app:
    build: .docker
    volumes:
      - ../:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  calisthenics-nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "89:80"
    volumes:
      - ../:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - calisthenics-app
